// Audit log codes in words (PO 10/10/2026: no raw codes on the console).
// Mirrors the `action` and `resourceType` values the backend writes today;
// anything new falls back to a neutral phrase until it is added here.

export const auditActionLabels: Record<string, string> = {
  ACCEPT: 'Nhận lời mời',
  APPROVE: 'Duyệt',
  BOOKING_CREATE: 'Tạo yêu cầu đặt lịch',
  BOOKING_DESCRIPTION_UPDATE: 'Sửa mô tả yêu cầu',
  BOOKING_RESCHEDULE: 'Đổi lịch hẹn',
  CANCELLATION_REVIEW: 'Xem xét huỷ đơn',
  CASH_SETTLEMENT_CONFIRMED: 'Xác nhận tiền mặt',
  CASH_SETTLEMENT_DECLARED: 'Khai tiền mặt',
  CASH_SETTLEMENT_DISPUTED: 'Khách báo sai lệch tiền mặt',
  CONFIG_UPDATE: 'Sửa cấu hình hệ thống',
  CREATE: 'Tạo mới',
  CUSTOMER_COMPLETION_CONFIRMED: 'Khách xác nhận hoàn tất',
  CUSTOMER_WALLET_ADJUSTMENT: 'Điều chỉnh ví khách',
  DEACTIVATE: 'Ngừng hoạt động',
  EVIDENCE_DELETE: 'Xoá ảnh bằng chứng',
  INVITATION_ACCEPT: 'Nhận lời mời',
  KYC_VERIFICATION_APPROVED: 'Duyệt hồ sơ kỹ thuật viên',
  KYC_VERIFICATION_REJECTED: 'Từ chối hồ sơ kỹ thuật viên',
  MATCHING_INVITATION_GROUP_EXTEND: 'Gia hạn tìm thợ',
  ORDER_COMPLETION_REQUESTED: 'Thợ báo hoàn thành',
  ORDER_DEPARTURE_WARNING: 'Nhắc thợ xuất phát',
  ORDER_TRANSITION: 'Đổi trạng thái đơn',
  PART_ACTIVATE: 'Mở bán linh kiện',
  PART_CREATE: 'Thêm linh kiện',
  PART_DEACTIVATE: 'Ngừng bán linh kiện',
  PART_ITEM_USAGE_UPDATED: 'Cập nhật dùng linh kiện',
  PART_REQUEST_CANCELLED: 'Huỷ yêu cầu linh kiện',
  PART_REQUEST_CASCADE_CANCELLED: 'Huỷ yêu cầu linh kiện theo đơn',
  PART_REQUEST_CREATED: 'Tạo yêu cầu linh kiện',
  PART_REQUEST_DELIVERING: 'Giao linh kiện',
  PART_REQUEST_QR_ROTATED: 'Tạo lại mã bàn giao',
  PART_REQUEST_READY: 'Chuẩn bị xong linh kiện',
  PART_REQUEST_RECEIVED: 'Thợ nhận linh kiện',
  PART_UPDATE: 'Sửa linh kiện',
  PAYMENT_VERIFIED: 'Xác nhận thanh toán',
  QUOTATION_CREATED: 'Lập báo giá',
  QUOTATION_DECISION: 'Khách duyệt hoặc từ chối báo giá',
  REVIEW_SUBMITTED: 'Khách đánh giá',
  SHORTLIST_CREATE: 'Chọn danh sách thợ',
  SKILL_VERIFICATION_APPROVED: 'Duyệt kỹ năng',
  SKILL_VERIFICATION_REJECTED: 'Từ chối kỹ năng',
  STRIKE_WAIVE: 'Miễn vi phạm',
  SUPPORT_CASE_HOLD_COMPLETION: 'Giữ đơn không tự hoàn tất',
  SUPPORT_CASE_RELEASE_COMPLETION: 'Bỏ giữ hoàn tất đơn',
  SUPPORT_CASE_RESOLVE: 'Xử lý yêu cầu hỗ trợ',
  SUPPORT_CASE_REVIEW_STARTED: 'Nhận xử lý yêu cầu hỗ trợ',
  TECHNICIAN_ACCOUNT_CREATED: 'Tạo tài khoản kỹ thuật viên',
  TECHNICIAN_MANUAL_ASSIGN: 'Gán thợ thủ công',
  TECHNICIAN_OVERRIDE_ASSIGNED: 'Gán thợ thay thế',
  TECHNICIAN_REPLACED_AFTER_REPORT: 'Đổi thợ theo báo cáo',
  TECHNICIAN_WITHDRAWAL_REMATCH: 'Tìm thợ khác khi thợ rút',
  UPDATE: 'Cập nhật',
  USER_STATUS_CHANGE: 'Đổi trạng thái tài khoản',
  WALLET_ADJUSTMENT: 'Điều chỉnh ví kỹ thuật viên',
  WARRANTY_CLAIM_ASSIGNED: 'Phân công bảo hành',
  WARRANTY_PROPOSAL_APPROVED: 'Duyệt kết luận bảo hành',
  WITHDRAWAL_PAID_OUT: 'Đã chi tiền rút',
  WITHDRAWAL_PAYOUT_FAILED: 'Chi tiền rút thất bại',
  WITHDRAWAL_REQUESTED: 'Yêu cầu rút tiền',
};

export const auditResourceLabels: Record<string, string> = {
  additional_cost_request: 'Chi phí phát sinh',
  booking: 'Yêu cầu đặt lịch',
  booking_invitation: 'Lời mời nhận việc',
  booking_invitation_group: 'Lượt mời thợ',
  cancellation: 'Huỷ đơn',
  cancellation_strike: 'Vi phạm khi huỷ',
  cash_settlement: 'Tiền mặt',
  customer_wallet: 'Ví khách',
  fixhome_part: 'Linh kiện',
  part_request: 'Yêu cầu linh kiện',
  part_request_item: 'Linh kiện trong yêu cầu',
  payment: 'Thanh toán',
  quotation: 'Báo giá',
  review: 'Đánh giá',
  service: 'Dịch vụ',
  service_area: 'Khu vực phục vụ',
  service_category: 'Danh mục dịch vụ',
  service_order: 'Đơn sửa chữa',
  service_orders: 'Đơn sửa chữa',
  support_case: 'Yêu cầu hỗ trợ',
  system_config: 'Cấu hình hệ thống',
  technician_bank_account: 'Tài khoản ngân hàng của thợ',
  technician_skill_verification: 'Kỹ năng kỹ thuật viên',
  technician_verification: 'Hồ sơ kỹ thuật viên',
  user: 'Tài khoản',
  wallet: 'Ví kỹ thuật viên',
  warranty_claim: 'Yêu cầu bảo hành',
  withdrawal_request: 'Rút tiền',
};

export const auditActionLabel = (action: string | null | undefined): string =>
  (action && auditActionLabels[action.toUpperCase()]) || 'Thao tác khác';

export const auditResourceLabel = (resource: string | null | undefined): string =>
  (resource && auditResourceLabels[resource.toLowerCase()]) || 'Đối tượng khác';
